language: go

go:
    - "1.6"
    - "1.7"
    - "1.8"
    - "1.9"
    - "1.10"
    - "1.11"

sudo: required

services:
    - docker

install:
    - docker build -f .travis/Dockerfile -t akio/rosgo .

script:
    - docker run akio/rosgo -v $GOROOT:/usr/local/go
